language: rust
rust: 
  # - stable
  # let's try only nightly for the moment
  - nightly

cache: cargo

script:
  # show info about bash and python as we use them
  # to execute nodes
  - bash --version
  - python3 --version
  - cargo build
  - cargo check
  - RUST_LOG=debug cargo test
  - cargo clippy
  - cargo fmt

branches:
  only:
    # Push and PR to master branch
    - master

