language: rust
rust: 
   - stable
   # nightly cause toolchain problems
   # - nightly

# matrix:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true

git:
  depth: 10

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - $TRAVIS_HOME/.cargo
    - /opt/pyenv/versions/3.6.3

# But don't cache the cargo registry
before_cache:
  - rm -rf $TRAVIS_HOME/.cargo/registry

before_install:
  # - pyenv install --list --> travis ci pyenv list goes to 3.6 and 3.7dev
  - pyenv install -s 3.6.3
  - pyenv global 3.6.3

install:
  - rustup component add rustfmt --toolchain $TRAVIS_RUST_VERSION

before_script:
  # show info about bash and python as we use them
  # to execute nodes
  - bash --version
  - python3 --version
  - rustup component add clippy
  - rustup component add rustfmt
    
script:
  - python3 scripts/check_version.py
  - cargo build
  - cargo check
  - RUST_LOG=debug cargo test --all-features
  # clippy failing on warnings
  - cargo clippy -- -D warnings
  - cargo fmt -- --check

branches:
  only:
    # Push and PR to master branch
    - master

deploy:
  - provider: script
    script: scripts/tag_branch.sh
