language: rust
rust: 
   - stable
   # nightly cause toolchain problems
   # - nightly

# matrix:
#   allow_failures:
#     - rust: nightly
#   fast_finish: true

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
cache:
  directories:
    - $TRAVIS_HOME/.cargo

# But don't cache the cargo registry
before_cache:
  - rm -rf $TRAVIS_HOME/.cargo/registry

install:
  - rustup component add rustfmt --toolchain $TRAVIS_RUST_VERSION
  - apt-get install -y python3.6

before_script:
  # show info about bash and python as we use them
  # to execute nodes
  - bash --version
  - python3.6 --version
  - rustup component add clippy
  - rustup component add rustfmt
    
script:
  - python3 scripts/check_version.py
  - cargo build
  - cargo check
  - RUST_LOG=debug cargo test --all-features
  # clippy failing on warnings
  - cargo clippy -- -D warnings
  - cargo fmt -- --check

branches:
  only:
    # Push and PR to master branch
    - master

