[package]
name = "yoshi"
version = "0.0.1"
authors = ["gnonpi <legnonpi@gmail.com>"]
edition = "2018"
description = "Build complex pipelines of batch jobs - inspired by Python's Luigi"
repository = "https://github.com/Gnonpi/yoshi"
documentation = "https://github.com/Gnonpi/yoshi"  # todo: change to hosted docs
readme = "README.md"

[badges]
# add crates.io badges

[dependencies]
